var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/skills/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x2io.4._.js")
R.c("server/chunks/ssr/0p91_next_dist_esm_build_templates_app-page_09yduq-.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lnk~yu._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_f196e._.js")
R.c("server/chunks/ssr/app_0_vqwfd._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_0fxmizk._.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_forbidden_0bh5o39.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_unauthorized_01vs8mb.js")
R.c("server/chunks/ssr/0p91_next_dist_client_components_builtin_global-error_03n.6~~.js")
R.c("server/chunks/ssr/_next-internal_server_app_skills_page_actions_0cxzzu-.js")
R.m(79730)
module.exports=R.m(79730).exports
